# Generated by Django 4.2.7 on 2026-03-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut_paiement',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Crédit'), ('partiel', 'Partiel')], default='non_paye', max_length=20),
        ),
    ]
