# Generated by Django 4.2.7 on 2026-07-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_mouvementstock_logactivite_parametre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogActivite',
        ),
    ]
