# Generated by Django 5.2.16 on 2026-07-20 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_harden_business_flows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositionformule',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compositions', to='user.mp'),
        ),
        migrations.AddConstraint(
            model_name='lotconsommation',
            constraint=models.CheckConstraint(condition=models.Q(('cout_unitaire__gte', 0)), name='allocation_cout_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='lotfournisseur',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__lte', models.F('quantite_initiale'))), name='lot_f_sous_initiale'),
        ),
        migrations.AddConstraint(
            model_name='lotpf',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__lte', models.F('quantite_initiale'))), name='lot_pf_sous_initiale'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lot_pf__isnull', True), ('mp__isnull', False)), models.Q(('lot_pf__isnull', False), ('mp__isnull', True)), _connector='OR'), name='mouvement_cible_coherente'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_avant__gte', 0)), name='mouvement_avant_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_apres__gte', 0)), name='mouvement_apres_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_delta', 0), _negated=True), name='mouvement_delta_non_nul'),
        ),
    ]
